name: colcon-bundle Integration Test
on:
  pull_request: # used for testing the PR
  schedule:
    - cron: '0 * * * *'
jobs:
  bundle_integration_test:
    name: ""
    strategy:
      fail-fast: false
      matrix:
        install_colcon_bundle_cmd:
          - "colcon-ros-bundle"
          - "git+https://github.com/colcon/colcon-bundle.git@master#egg=colcon-bundle git+https://github.com/colcon/colcon-ros-bundle.git@master#egg=colcon-ros-bundle"
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-xenial-ros-kinetic-ros-base-latest
    steps:
      - name: setup-ros-docker#7 workaround
        run: sudo chown -R rosbuild:rosbuild "$HOME" .
      - uses: ros-tooling/action-ros-ci@0.0.17
        id: build-from-repos
        with:
          vcs-repo-file-url: "${{ github.workspace }}/.github/workflows/test_bundle.repos"
          package-name: ros_tutorials navigation
          source-ros-binary-installation: kinetic
      - name: Install colcon-bundle dependencies
        run: |
          sudo apt update
          sudo apt -y install python3-apt python3-pip
          sudo pip3 install -U setuptools==44.0.0
      - name: Install ${{ matrix.install_colcon_bundle_cmd }}
        run: sudo pip3 install -U ${{ matrix.install_colcon_bundle_cmd }}
      - name: Run colcon bundle
        run: |
          cd "${{ steps.build-from-repos.outputs.ros-workspace-directory-name }}"
          colcon bundle
